version: '3.8'
services:
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  server:
    build: .
    command: python -m server
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
